apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-blue
  labels:
    app: order-service
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      color: blue
  template:
    metadata:
      labels:
        app: order-service
        color: blue
    spec:
      containers:
        - name: order-service
          image: your-ecr-url/order-service:IMAGE_TAG
          ports:
            - containerPort: 3000
