apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-blue
  labels:
    app: user-service
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      color: blue
  template:
    metadata:
      labels:
        app: user-service
        color: blue
    spec:
      containers:
        - name: user-service
          image: your-ecr-url/user-service:IMAGE_TAG
          ports:
            - containerPort: 3000
