apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-green
  labels:
    app: auth-service
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
      color: green
  template:
    metadata:
      labels:
        app: auth-service
        color: green
    spec:
      containers:
        - name: auth-service
          image: your-ecr-url/auth-service:IMAGE_TAG
          ports:
            - containerPort: 3000
