apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-green
  labels:
    app: payment-service
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
      color: green
  template:
    metadata:
      labels:
        app: payment-service
        color: green
    spec:
      containers:
        - name: payment-service
          image: your-ecr-url/payment-service:IMAGE_TAG
          ports:
            - containerPort: 3000
