apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-green
  labels:
    app: notification-service
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
      color: green
  template:
    metadata:
      labels:
        app: notification-service
        color: green
    spec:
      containers:
        - name: notification-service
          image: your-ecr-url/notification-service:IMAGE_TAG
          ports:
            - containerPort: 3000
