apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-blue
  labels:
    app: auth-service
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
      color: blue
  template:
    metadata:
      labels:
        app: auth-service
        color: blue
    spec:
      containers:
        - name: auth-service
          image: your-ecr-url/auth-service:IMAGE_TAG
          ports:
            - containerPort: 3000
